WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a4dc10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb/element
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a4e310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb/element
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a4ee10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb/element
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a50590>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a50c10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110a51410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/ed1a4b462653c1ab7e23dccd0a6d84fb